all:
	gcc -o par_impar par_impar.c queue.c
	gcc -o par_impar_codeblocks par_impar_codeblocks.c 
	gcc -o islands islands.c pqueue.c
	gcc -o imagens imagens.c pqueue.c
	gcc -o jackpot jackpot.c queue.c
	gcc -o josephus josephus.c queue.c
clean:
	rm par_impar par_impar_codeblocks islands imagens jackpot josephus
